name: tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Cache python packages
      uses: actions/cache@v3
      env:
        cache-name: test-python-packages
      with:
        path: '~/.local/**/site-packages'
        key: ${{ runner.os }}-${{ matrix.python }}-${{ env.cache-name }}-${{ hashFiles('requirements/**/*.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.python }}-${{ env.cache-name }}-

    - name: Install gdal-bin
      run: |
        sudo apt-get -qq update
        sudo apt-get -y install gdal-bin

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/base.txt --user
        pip install -r requirements/tests.txt --user
        pip install -r requirements/lint.txt --user

    - name: Check with black
      run: |
        python -m black --check skytek_utils

    - name: Check with isort
      run: |
        python -m isort --check-only skytek_utils

    - name: Check with pylint
      run: |
        ./lint_all.sh

    - name: Test with pytest
      run: |
        python -m pytest tests
